language: cpp

dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:nuspell/ppa'
    packages:
      - libglib2.0-dev
      - libaspell-dev
      - hspell
      - libhunspell-dev
      - libvoikko-dev
      - voikko-fi
      - aspell-en
      - libunittest++-dev
      - hunspell-fr
      - libhunspell-dev

env:
  global:
    - VERBOSE=1 # Get test logs in Travis logs

matrix:
  include:
    - os: linux
      arch:
        - ppc64le
        - amd64
      env:
        - CONFIGURE_ARGS=("CFLAGS=\"-g3 -fsanitize=address -fsanitize=undefined\"" "LDFLAGS=\"-fsanitize=address -fsanitize=undefined\"")
    - os: osx

before_install:
  # Note: aspell should work on macOS, but has been removed from the next
  # line because one of the tests fails; see
  # https://github.com/Homebrew/homebrew-core/issues/40976
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install dbus-glib hspell hunspell libvoikko unittest-cpp ; fi

script:
  - ./bootstrap
  - ./configure --enable-relocatable --with-zemberek=check "${CONFIGURE_ARGS[@]}"
  - make
  - make distcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo locale-gen fr_FR.UTF-8; env LANG=fr_FR.UTF-8 make check ; fi
