language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - libglib2.0-dev
      - libdbus-glib-1-dev
      - libaspell-dev
      - ispell
      - hspell
      - libhunspell-dev
      - libvoikko-dev
      - aspell-en
      # - zemberek-server: installs with error in Travisâ€™s trusty environment

env: &default_env
  - VERBOSE=1 # Get test logs in Travis logs

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.2
    - compiler: gcc
      env:
        - *default_env
        - COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [g++-5]
    - compiler: gcc
      env:
        - *default_env
        - COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [g++-6]

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib dbus-glib aspell hspell hunspell libvoikko ispell ; fi

script:
  - ./autogen.sh
  - make
  - make distcheck
