language: cpp

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - libglib2.0-dev
      - libaspell-dev
      - hspell
      - libhunspell-dev
      - libvoikko-dev
      - voikko-fi
      - aspell-en
      - libunittest++-dev
      - valgrind
      - g++-5

env:
  global:
    - VERBOSE=1 # Get test logs in Travis logs

matrix:
  include:
    - os: linux
      env:
        - COMPILER=g++-5
    - os: osx
      osx_image: xcode9.2
    - compiler: gcc
      env:
        - COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [g++-6]

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  # Note: aspell should work on macOS, but has been removed from the next
  # line because one of the tests fails; see
  # https://github.com/Homebrew/homebrew-core/issues/40976
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib dbus-glib hspell hunspell libvoikko unittest-cpp ; fi

script:
  - ./bootstrap
  - ./configure --enable-relocatable --with-zemberek=check CXX=$COMPILER
  - make
  - make distcheck
